services:
  - type: web
    name: smartspend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run smartspend.py --server.port 10000 --server.address 0.0.0.0"
    plan: free